### ISSUE TITLE
global variables

### ISSUE THREAD

**Issue by Tsenzuk** [mirantel/learn_d3#1]
https://github.com/mirantel/learn_d3/blob/28de37b3c0fa00f6d8360240ad2cbe5a89fef4cc/lineChart/index.js#L247

please avoid global variables. Instead of `varname = somthing,` provide these `somthing`s as arguments and names of them should be listed when function is declared: `funtion yourFunc(varname1, varname2, ...)`

**Comment by mirantel** [comment]
Thank you, today I fix this issue.
